#%Dialect 1.0
uses:
  partyrole_eg: ../PartyRole/schema.yaml
  account_eg: ../Account/schema.yaml
  contactpoint_eg: ../ContactPoint/schema.yaml
nodeMappings:
  PartyRelationshipType:
    classTerm: cim.PartyRelationshipType
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      relatedPartyRole:
        propertyTerm: cim.relatedPartyRole
        range: string
        mandatory: true
      partyRole:
        propertyTerm: cim.partyRole
        range: string
        mandatory: true
      isBidirectional:
        propertyTerm: cim.isBidirectional
        range: boolean
        mandatory: true
  PersonEducation:
    classTerm: cim.PersonEducation
    mapping:
      individual:
        propertyTerm: cim.individual
        range: Individual
        mandatory: true
        allowMultiple: true
      graduationDate:
        propertyTerm: cim.graduationDate
        range: date
        mandatory: true
      educationLevel:
        propertyTerm: cim.educationLevel
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      institutionName:
        propertyTerm: cim.institutionName
        range: string
        mandatory: true
      educationName:
        propertyTerm: cim.educationName
        range: string
        mandatory: true
  PartyIdentification:
    classTerm: cim.PartyIdentification
    mapping:
      expiryDate:
        propertyTerm: cim.expiryDate
        range: date
      partyRole:
        propertyTerm: cim.partyRole
        range: partyrole_eg.PartyRole
        allowMultiple: true
      issuedDate:
        propertyTerm: cim.issuedDate
        range: date
      party:
        propertyTerm: cim.party
        range: Party
        mandatory: true
        allowMultiple: true
      identificationNumber:
        propertyTerm: cim.identificationNumber
        range: string
        mandatory: true
      issuedAtLocation:
        propertyTerm: cim.issuedAtLocation
        range: string
      partyIdentificationType:
        propertyTerm: cim.partyIdentificationType
        range: string
        mandatory: true
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
      issuedByAuthority:
        propertyTerm: cim.issuedByAuthority
        range: string
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      verifiedDate:
        propertyTerm: cim.verifiedDate
        range: date
  PersonLanguage:
    classTerm: cim.PersonLanguage
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      writtenProficiencyLevel:
        propertyTerm: cim.writtenProficiencyLevel
        range: string
      spokenProficiencyLevel:
        propertyTerm: cim.spokenProficiencyLevel
        range: string
      individual:
        propertyTerm: cim.individual
        range: Individual
        mandatory: true
        allowMultiple: true
  InternalBusinessUnit:
    classTerm: cim.InternalBusinessUnit
    mapping:
      parentInternalBusinessUnit:
        propertyTerm: cim.parentInternalBusinessUnit
        range: InternalBusinessUnit
        allowMultiple: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      businessUnitType:
        propertyTerm: cim.businessUnitType
        range: string
        mandatory: true
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
    extends: Party
  PartyRelatedParty:
    classTerm: cim.PartyRelatedParty
    mapping:
      relatedToDate:
        propertyTerm: cim.relatedToDate
        range: date
        mandatory: true
      partyRelationshipType:
        propertyTerm: cim.partyRelationshipType
        range: PartyRelationshipType
        mandatory: true
        allowMultiple: true
      relatedFromDate:
        propertyTerm: cim.relatedFromDate
        range: date
        mandatory: true
      relatedParty:
        propertyTerm: cim.relatedParty
        range: Party
        mandatory: true
        allowMultiple: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      party:
        propertyTerm: cim.party
        range: Party
        mandatory: true
        allowMultiple: true
  Party:
    classTerm: cim.Party
    mapping:
      noMergeReason:
        propertyTerm: cim.noMergeReason
        range: string
      globalParty:
        propertyTerm: cim.globalParty
        range: string
      primaryAccount:
        propertyTerm: cim.primaryAccount
        range: account_eg.Account
        allowMultiple: true
      partyType:
        propertyTerm: cim.partyType
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
  Household:
    classTerm: cim.Household
    mapping:
      householdMemberCount:
        propertyTerm: cim.householdMemberCount
        range: integer
      householdDissolvedDate:
        propertyTerm: cim.householdDissolvedDate
        range: date
      householdFormedDate:
        propertyTerm: cim.householdFormedDate
        range: date
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
    extends: Party
  UncategorizedParty:
    classTerm: cim.UncategorizedParty
    mapping:
      originalSourceRecord:
        propertyTerm: cim.originalSourceRecord
        range: string
      uncategorizedPartyLabel:
        propertyTerm: cim.uncategorizedPartyLabel
        range: string
        mandatory: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      creationReason:
        propertyTerm: cim.creationReason
        range: string
      originalSourceSystem:
        propertyTerm: cim.originalSourceSystem
        range: string
    extends: Party
  PersonEmployment:
    classTerm: cim.PersonEmployment
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      employerAddressLine4:
        propertyTerm: cim.employerAddressLine4
        range: string
      employerPhoneNumber:
        propertyTerm: cim.employerPhoneNumber
        range: string
        mandatory: true
      employerAddressLine3:
        propertyTerm: cim.employerAddressLine3
        range: string
      employerName:
        propertyTerm: cim.employerName
        range: string
        mandatory: true
      employerAddressLine1:
        propertyTerm: cim.employerAddressLine1
        range: string
        mandatory: true
      positionText:
        propertyTerm: cim.positionText
        range: string
        mandatory: true
      employerCityName:
        propertyTerm: cim.employerCityName
        range: string
      occupationText:
        propertyTerm: cim.occupationText
        range: string
        mandatory: true
      individual:
        propertyTerm: cim.individual
        range: Individual
        mandatory: true
        allowMultiple: true
      employmentStatus:
        propertyTerm: cim.employmentStatus
        range: string
        mandatory: true
      annualIncome:
        propertyTerm: cim.annualIncome
        range: integer
        mandatory: true
      endDate:
        propertyTerm: cim.endDate
        range: date
        mandatory: true
      employerPostalCodeText:
        propertyTerm: cim.employerPostalCodeText
        range: string
      employerContactPointAddress:
        propertyTerm: cim.employerContactPointAddress
        range: contactpoint_eg.ContactPointAddress
        allowMultiple: true
      employerAddressLine2:
        propertyTerm: cim.employerAddressLine2
        range: string
      startDate:
        propertyTerm: cim.startDate
        range: date
        mandatory: true
  PartyAdditionalName:
    classTerm: cim.PartyAdditionalName
    mapping:
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      name:
        propertyTerm: cim.name
        range: string
        mandatory: true
      additionalNameType:
        propertyTerm: cim.additionalNameType
        range: string
        mandatory: true
      party:
        propertyTerm: cim.party
        range: Party
        mandatory: true
        allowMultiple: true
  Individual:
    classTerm: cim.Individual
    mapping:
      photoURL:
        propertyTerm: cim.photoURL
        range: string
      isAlcoholConsumer:
        propertyTerm: cim.isAlcoholConsumer
        range: boolean
      yearlyIncomeRange:
        propertyTerm: cim.yearlyIncomeRange
        range: string
      doNotProcessFromUpdateDate:
        propertyTerm: cim.doNotProcessFromUpdateDate
        range: date
      childrenCount:
        propertyTerm: cim.childrenCount
        range: integer
      mainDietaryHabitType:
        propertyTerm: cim.mainDietaryHabitType
        range: string
      isHighRiskHobby:
        propertyTerm: cim.isHighRiskHobby
        range: boolean
      birthPlace:
        propertyTerm: cim.birthPlace
        range: string
      doNotProcessReason:
        propertyTerm: cim.doNotProcessReason
        range: string
      gender:
        propertyTerm: cim.gender
        range: string
      mainDisabilityType:
        propertyTerm: cim.mainDisabilityType
        range: string
      consumerCreditScoreProviderName:
        propertyTerm: cim.consumerCreditScoreProviderName
        range: string
      personHeightUnitOfMeasure:
        propertyTerm: cim.personHeightUnitOfMeasure
        range: string
      hasDrugAbuseHistory:
        propertyTerm: cim.hasDrugAbuseHistory
        range: boolean
      surgeriesLast5YearsCount:
        propertyTerm: cim.surgeriesLast5YearsCount
        range: integer
      influencerRating:
        propertyTerm: cim.influencerRating
        range: integer
      netWorth:
        propertyTerm: cim.netWorth
        range: integer
      personLifeStage:
        propertyTerm: cim.personLifeStage
        range: string
      middleName:
        propertyTerm: cim.middleName
        range: string
      sendIndividualData:
        propertyTerm: cim.sendIndividualData
        range: boolean
      militaryStatus:
        propertyTerm: cim.militaryStatus
        range: string
      personWeightUnitOfMeasure:
        propertyTerm: cim.personWeightUnitOfMeasure
        range: string
      occupation:
        propertyTerm: cim.occupation
        range: string
      yearlyIncome:
        propertyTerm: cim.yearlyIncome
        range: integer
      firstName:
        propertyTerm: cim.firstName
        range: string
      hasAlcoholAbuseHistory:
        propertyTerm: cim.hasAlcoholAbuseHistory
        range: boolean
      primaryHobby:
        propertyTerm: cim.primaryHobby
        range: string
      mailingName:
        propertyTerm: cim.mailingName
        range: string
      lastName:
        propertyTerm: cim.lastName
        range: string
      mainLifeStyleType:
        propertyTerm: cim.mainLifeStyleType
        range: string
      occupationType:
        propertyTerm: cim.occupationType
        range: string
      taxBracketRange:
        propertyTerm: cim.taxBracketRange
        range: string
      secondLastName:
        propertyTerm: cim.secondLastName
        range: string
      overAgeNumber:
        propertyTerm: cim.overAgeNumber
        range: integer
      preferredName:
        propertyTerm: cim.preferredName
        range: string
      highestEducationLevel:
        propertyTerm: cim.highestEducationLevel
        range: string
      doNotTrackLocationUpdateDate:
        propertyTerm: cim.doNotTrackLocationUpdateDate
        range: date
      doNotProfileFromUpdateDate:
        propertyTerm: cim.doNotProfileFromUpdateDate
        range: date
      dependentCount:
        propertyTerm: cim.dependentCount
        range: integer
      birthDate:
        propertyTerm: cim.birthDate
        range: date
      mainPersonalValueType:
        propertyTerm: cim.mainPersonalValueType
        range: string
      mothersMaidenName:
        propertyTerm: cim.mothersMaidenName
        range: string
      convictionsCount:
        propertyTerm: cim.convictionsCount
        range: integer
      doExtractMyDataUpdateDate:
        propertyTerm: cim.doExtractMyDataUpdateDate
        range: date
      isTobaccoConsume:
        propertyTerm: cim.isTobaccoConsume
        range: boolean
      militaryService:
        propertyTerm: cim.militaryService
        range: string
      isGoodStudent:
        propertyTerm: cim.isGoodStudent
        range: boolean
      doForgetMeFromUpdateDate:
        propertyTerm: cim.doForgetMeFromUpdateDate
        range: date
      ethnicity:
        propertyTerm: cim.ethnicity
        range: string
      isHighRiskOccupation:
        propertyTerm: cim.isHighRiskOccupation
        range: boolean
      salutation:
        propertyTerm: cim.salutation
        range: string
      deathPlace:
        propertyTerm: cim.deathPlace
        range: string
      doNotTrackUpdateDate:
        propertyTerm: cim.doNotTrackUpdateDate
        range: date
      weddingAnniversaryDate:
        propertyTerm: cim.weddingAnniversaryDate
        range: date
      primaryHousehold:
        propertyTerm: cim.primaryHousehold
        range: Household
        allowMultiple: true
      mainPersonalityType:
        propertyTerm: cim.mainPersonalityType
        range: string
      hospitalizationsLast5YearsCount:
        propertyTerm: cim.hospitalizationsLast5YearsCount
        range: integer
      currentEmployerName:
        propertyTerm: cim.currentEmployerName
        range: string
      mainLifeAttitudeType:
        propertyTerm: cim.mainLifeAttitudeType
        range: string
      isGoodDriver:
        propertyTerm: cim.isGoodDriver
        range: boolean
      orderingName:
        propertyTerm: cim.orderingName
        range: string
      personWeight:
        propertyTerm: cim.personWeight
        range: integer
      minorCitationCount:
        propertyTerm: cim.minorCitationCount
        range: integer
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
      doNotMarketFromUpdateDate:
        propertyTerm: cim.doNotMarketFromUpdateDate
        range: date
      religion:
        propertyTerm: cim.religion
        range: string
      nameSuffix:
        propertyTerm: cim.nameSuffix
        range: string
      personName:
        propertyTerm: cim.personName
        range: string
        mandatory: true
      personHeight:
        propertyTerm: cim.personHeight
        range: integer
      isHomeOwner:
        propertyTerm: cim.isHomeOwner
        range: boolean
      residenceCaptureMethod:
        propertyTerm: cim.residenceCaptureMethod
        range: string
      shouldForget:
        propertyTerm: cim.shouldForget
        range: boolean
      officialName:
        propertyTerm: cim.officialName
        range: string
      employedSinceDate:
        propertyTerm: cim.employedSinceDate
        range: date
      residenceCountryName:
        propertyTerm: cim.residenceCountryName
        range: string
      maritalStatus:
        propertyTerm: cim.maritalStatus
        range: string
      consumerCreditScore:
        propertyTerm: cim.consumerCreditScore
        range: integer
      isDrugConsumer:
        propertyTerm: cim.isDrugConsumer
        range: boolean
      deathDate:
        propertyTerm: cim.deathDate
        range: date
      webSiteURL:
        propertyTerm: cim.webSiteURL
        range: string
      majorCitationCount:
        propertyTerm: cim.majorCitationCount
        range: integer
    extends: Party
  PersonLifeEvent:
    classTerm: cim.PersonLifeEvent
    mapping:
      personLifeEventDateTime:
        propertyTerm: cim.personLifeEventDateTime
        range: time
        mandatory: true
      personLifeEventType:
        propertyTerm: cim.personLifeEventType
        range: string
        mandatory: true
      individual:
        propertyTerm: cim.individual
        range: Individual
        mandatory: true
        allowMultiple: true
      id:
        propertyTerm: cim.id
        range: guid
        unique: true
        mandatory: true
external:
  cim: http://cloudinformationmodel.org/model/
dialect: PartyEntityGroup
version: "0.1"
documents:
  root:
    declares:
      PartyRelationshipTypeSchemas: PartyRelationshipType
      PersonEducationSchemas: PersonEducation
      PartyIdentificationSchemas: PartyIdentification
      PersonLanguageSchemas: PersonLanguage
      InternalBusinessUnitSchemas: InternalBusinessUnit
      PartyRelatedPartySchemas: PartyRelatedParty
      PartySchemas: Party
      HouseholdSchemas: Household
      UncategorizedPartySchemas: UncategorizedParty
      PersonEmploymentSchemas: PersonEmployment
      PartyAdditionalNameSchemas: PartyAdditionalName
      IndividualSchemas: Individual
      PersonLifeEventSchemas: PersonLifeEvent
  fragments:
    encodes:
      PartyRelationshipType: PartyRelationshipType
      PersonEducation: PersonEducation
      PartyIdentification: PartyIdentification
      PersonLanguage: PersonLanguage
      InternalBusinessUnit: InternalBusinessUnit
      PartyRelatedParty: PartyRelatedParty
      Party: Party
      Household: Household
      UncategorizedParty: UncategorizedParty
      PersonEmployment: PersonEmployment
      PartyAdditionalName: PartyAdditionalName
      Individual: Individual
      PersonLifeEvent: PersonLifeEvent