#%RAML 1.0 Library
types:
  UncategorizedParty:
    type: Party
    properties:
      creationReason:
        type: string
      id:
        type: string
      uncategorizedPartyLabel:
        type: string
      originalSourceRecord:
        type: string
      originalSourceSystem:
        type: string
  PersonLanguage:
    properties:
      individual:
        items: Individual
      id:
        type: string
      spokenProficiencyLevel:
        type: string
      writtenProficiencyLevel:
        type: string
  PersonEducation:
    properties:
      id:
        type: string
      educationLevel:
        type: string
      educationName:
        type: string
      graduationDate:
        type: date-only
      individual:
        items: Individual
      institutionName:
        type: string
  Individual:
    type: Party
    properties:
      hasAlcoholAbuseHistory:
        type: boolean
      highestEducationLevel:
        type: string
      personHeight:
        type: integer
      mailingName:
        type: string
      surgeriesLast5YearsCount:
        type: integer
      doNotTrackUpdateDate:
        type: date-only
      weddingAnniversaryDate:
        type: date-only
      minorCitationCount:
        type: integer
      mainDietaryHabitType:
        type: string
      personHeightUnitOfMeasure:
        type: string
      firstName:
        type: string
      personName:
        type: string
      photoURL:
        type: string
      isHighRiskHobby:
        type: boolean
      doNotProcessFromUpdateDate:
        type: date-only
      militaryService:
        type: string
      maritalStatus:
        type: string
      doNotMarketFromUpdateDate:
        type: date-only
      shouldForget:
        type: boolean
      id:
        type: string
      mainDisabilityType:
        type: string
      consumerCreditScoreProviderName:
        type: string
      isTobaccoConsume:
        type: boolean
      webSiteURL:
        type: string
      secondLastName:
        type: string
      primaryHousehold:
        items: Household
      orderingName:
        type: string
      hospitalizationsLast5YearsCount:
        type: integer
      dependentCount:
        type: integer
      convictionsCount:
        type: integer
      isGoodDriver:
        type: boolean
      primaryHobby:
        type: string
      mainPersonalValueType:
        type: string
      isAlcoholConsumer:
        type: boolean
      taxBracketRange:
        type: string
      childrenCount:
        type: integer
      isGoodStudent:
        type: boolean
      mainLifeAttitudeType:
        type: string
      netWorth:
        type: integer
      personWeight:
        type: integer
      birthDate:
        type: date-only
      religion:
        type: string
      sendIndividualData:
        type: boolean
      deathDate:
        type: date-only
      doExtractMyDataUpdateDate:
        type: date-only
      birthPlace:
        type: string
      overAgeNumber:
        type: integer
      doForgetMeFromUpdateDate:
        type: date-only
      personWeightUnitOfMeasure:
        type: string
      mainLifeStyleType:
        type: string
      gender:
        type: string
      hasDrugAbuseHistory:
        type: boolean
      salutation:
        type: string
      mothersMaidenName:
        type: string
      doNotTrackLocationUpdateDate:
        type: date-only
      ethnicity:
        type: string
      mainPersonalityType:
        type: string
      employedSinceDate:
        type: date-only
      officialName:
        type: string
      isHighRiskOccupation:
        type: boolean
      residenceCaptureMethod:
        type: string
      doNotProfileFromUpdateDate:
        type: date-only
      nameSuffix:
        type: string
      isDrugConsumer:
        type: boolean
      isHomeOwner:
        type: boolean
      doNotProcessReason:
        type: string
      occupationType:
        type: string
      deathPlace:
        type: string
      influencerRating:
        type: integer
      militaryStatus:
        type: string
      consumerCreditScore:
        type: integer
      yearlyIncome:
        type: integer
      preferredName:
        type: string
      personLifeStage:
        type: string
      yearlyIncomeRange:
        type: string
      majorCitationCount:
        type: integer
      middleName:
        type: string
      residenceCountryName:
        type: string
      lastName:
        type: string
      occupation:
        type: string
      currentEmployerName:
        type: string
  PersonEmployment:
    properties:
      employmentStatus:
        type: string
      positionText:
        type: string
      employerContactPointAddress:
        items: contactpoint_eg.ContactPointAddress
      employerAddressLine3:
        type: string
      endDate:
        type: date-only
      startDate:
        type: date-only
      occupationText:
        type: string
      id:
        type: string
      employerName:
        type: string
      employerAddressLine4:
        type: string
      employerAddressLine1:
        type: string
      annualIncome:
        type: integer
      employerCityName:
        type: string
      individual:
        items: Individual
      employerAddressLine2:
        type: string
      employerPostalCodeText:
        type: string
      employerPhoneNumber:
        type: string
  PartyIdentification:
    properties:
      expiryDate:
        type: date-only
      partyIdentificationType:
        type: string
      verifiedDate:
        type: date-only
      issuedByAuthority:
        type: string
      issuedAtLocation:
        type: string
      issuedDate:
        type: date-only
      partyRole:
        type: string
      id:
        type: string
      name:
        type: string
      identificationNumber:
        type: string
      party:
        items: Party
  PartyRelatedParty:
    properties:
      relatedFromDate:
        type: date-only
      id:
        type: string
      partyRelationshipType:
        items: PartyRelationshipType
      relatedParty:
        items: Party
      relatedToDate:
        type: date-only
      party:
        items: Party
  PartyAdditionalName:
    properties:
      id:
        type: string
      additionalNameType:
        type: string
      name:
        type: string
      party:
        items: Party
  PartyRelationshipType:
    properties:
      isBidirectional:
        type: boolean
      id:
        type: string
      partyRole:
        type: string
      relatedPartyRole:
        type: string
  Household:
    type: Party
    properties:
      householdMemberCount:
        type: integer
      householdFormedDate:
        type: date-only
      id:
        type: string
      name:
        type: string
      householdDissolvedDate:
        type: date-only
  PersonLifeEvent:
    properties:
      individual:
        items: Individual
      id:
        type: string
      personLifeEventDateTime:
        type: time-only
      personLifeEventType:
        type: string
  Party:
    properties:
      partyType:
        type: string
      id:
        type: string
      globalParty:
        type: string
      noMergeReason:
        type: string
      primaryAccount:
        items: account_eg.Account
  InternalBusinessUnit:
    type: Party
    properties:
      id:
        type: string
      businessUnitType:
        type: string
      parentInternalBusinessUnit:
        items: InternalBusinessUnit
      name:
        type: string
uses:
  account_eg: ../Account/schema.yaml
  contactpoint_eg: ../ContactPoint/schema.yaml
