CREATE SCHEMA IF NOT EXISTS PRODUCT_ENTITY_GROUP;

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_RELATED_PRODUCT (
  ID VARCHAR(36) UNIQUE NOT NULL,
  NAME VARCHAR(500) NOT NULL,
  IS_DEFAULT_OPTION BOOLEAN NOT NULL,
  FROM_DATE DATE NOT NULL,
  TO_DATE DATE,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_TRANSLATION (
  LONG_DESCRIPTION VARCHAR(500),
  DESCRIPTION VARCHAR(500),
  ID VARCHAR(36) UNIQUE NOT NULL,
  NAME VARCHAR(500) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_IMAGE (
  ID VARCHAR(36) UNIQUE NOT NULL,
  IS_DEFAULT_IMAGE BOOLEAN NOT NULL,
  IMAGE_VIEW_TYPE VARCHAR(500),
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_RELATIONSHIP_TYPE (
  ID VARCHAR(36) UNIQUE NOT NULL,
  PARENT_PRODUCT_ROLE VARCHAR(500) NOT NULL,
  CHILD_PRODUCT_ROLE VARCHAR(500) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_IMAGE_TRANSLATION (
  ID VARCHAR(36) UNIQUE NOT NULL,
  TRANSLATED_NAME VARCHAR(500) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.GOODS_PRODUCT (
  PRODUCT_SECURITY_REQUIREMENT VARCHAR(500),
  SEASON VARCHAR(500),
  COLOR VARCHAR(500),
  STYLE VARCHAR(500),
  IS_MADE_TO_ORDER BOOLEAN NOT NULL,
  HEIGHT INTEGER,
  FABRIC VARCHAR(500),
  REQUIRED_TEMPERATURE_UO_M VARCHAR(500),
  SHELF_FACING_UNIT_COUNT INTEGER,
  REQUIRED_HUMIDITY_PERCENTAGE INTEGER,
  ID VARCHAR(36) UNIQUE NOT NULL,
  GROSS_WEIGHT INTEGER,
  TARE_WEIGHT INTEGER,
  DEPTH INTEGER,
  REQUIRED_TEMPERATURE_LOWEST_NUMBER INTEGER,
  GENDER VARCHAR(500),
  MAX_HOLDING_DAY_COUNT INTEGER,
  DIAMETER INTEGER,
  IS_PERISHABLE BOOLEAN NOT NULL,
  REQUIRED_CLEANUP_PROCESS VARCHAR(500),
  PATTERN VARCHAR(500),
  REQUIRED_TEMPERATURE_HIGHEST_NUMBER INTEGER,
  NET_WEIGHT INTEGER,
  ENVIRONMENT_REQUIREMENT VARCHAR(500),
  DRAINED_WEIGHT INTEGER,
  AGE VARCHAR(500),
  WIDTH INTEGER,
  REQUIRES_UNIT_PRICE_LABEL BOOLEAN NOT NULL,
  WEIGHT_UO_M VARCHAR(500),
  PRODUCT_MAY_EXPAND BOOLEAN NOT NULL,
  SIZE_UO_M VARCHAR(500),
  QUANTITY_SCHEDULE_TYPE VARCHAR(500),
  DISPOSAL_TYPE VARCHAR(500),
  LONG_DESCRIPTION VARCHAR(500) NOT NULL,
  MINIMUM_ADVERTISEMENT_AMOUNT INTEGER,
  IS_BACK_ORDERED BOOLEAN NOT NULL,
  VALID_FOR_PERIOD_COUNT INTEGER,
  IS_WORKER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  ALLOW_PARTIAL_REFUND BOOLEAN,
  IS_WEIGHT_ENTRY_REQUIRED BOOLEAN NOT NULL,
  IS_QUANTITY_ENTRY_REQUIRED BOOLEAN NOT NULL,
  IS_SERIALIZED BOOLEAN NOT NULL,
  REWARD_PROGRAM_POINTS_COUNT INTEGER,
  DESCRIPTION VARCHAR(500) NOT NULL,
  REVENUE_INSTALLMENT_PERIOD VARCHAR(500),
  NAME VARCHAR(500) NOT NULL,
  IS_AUTO_PROVISIONABLE BOOLEAN NOT NULL,
  IS_COUPON_REDEMPTION_ALLOWED BOOLEAN NOT NULL,
  IS_SELLABLE_INDEPENDENTLY BOOLEAN NOT NULL,
  CAN_USE_REVENUE_SCHEDULE BOOLEAN NOT NULL,
  MANUFACTURER_NAME VARCHAR(500),
  IS_INTELLECTUAL_PROPERTY_PROTECTED BOOLEAN,
  MODEL_YEAR INTEGER,
  IS_CUSTOMER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  PRODUCT_STATUS VARCHAR(500) NOT NULL,
  BRAND_GRADE VARCHAR(500),
  QUANTITY_INSTALLMENT_COUNT INTEGER,
  REQUIRED_DEPOSIT_AMOUNT INTEGER,
  REVENUE_SCHEDULE_TYPE VARCHAR(500),
  IS_PRE_ORDERABLE BOOLEAN NOT NULL,
  REQUIRES_INVIDIDUAL_UNIT_PRICING BOOLEAN NOT NULL,
  STANDARD_WARRANTY_LENGTH_MONTH INTEGER,
  CAN_USE_QUANTITY_SCHEDULE BOOLEAN NOT NULL,
  IS_INSTALLABLE BOOLEAN NOT NULL,
  IS_RAIN_CHECK_ALLOWED BOOLEAN NOT NULL,
  MINIMUM_ADVERTISEMENT_AMOUNT_START_DATE INTEGER,
  MAXIMUM_ORDER_QUANTITY_COUNT INTEGER,
  IS_MULTIPLE_COUPONS_ALLOWED BOOLEAN NOT NULL,
  ALLOW_CUSTOMER_RETURN BOOLEAN,
  MODEL_NUMBER VARCHAR(500),
  M_SR_PAMOUNT INTEGER,
  EXTERNAL_SOURCE_RECORD VARCHAR(500),
  IS_SELLABLE BOOLEAN,
  VALID_TO_DATE DATE,
  PRICE_CHARGE_TYPE VARCHAR(500) NOT NULL,
  IS_PARTNER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  REVENUE_INSTALLMENT_COUNT INTEGER,
  PRODUCT_SK_U VARCHAR(500) NOT NULL,
  QUANTITY_INSTALLMENT_PERIOD VARCHAR(500),
  IS_MANUAL_PRICE_ENTRY_REQUIRED BOOLEAN NOT NULL,
  TYPE VARCHAR(500),
  IS_SELLABLE_WITHOUT_PRICE BOOLEAN NOT NULL,
  GL_ACCOUNT_CODE VARCHAR(500),
  IS_RETURNABLE BOOLEAN NOT NULL,
  DISPLAY_URL VARCHAR(500),
  VERSION_NUMBER VARCHAR(500),
  LOT_IDENTIFIER VARCHAR(500),
  VALID_FROM_DATE DATE,
  STOCK_LEDGER_VALUATION_AMOUNT INTEGER,
  IS_DYNAMIC_BUNDLE BOOLEAN NOT NULL,
  IS_QUALITY_VERIFICATION_REQUIRED BOOLEAN NOT NULL,
  REQUIRED_DEPOSIT_PERCENTAGE INTEGER,
  IS_FOODSTAMP_PAYMENT_ALLOWED BOOLEAN NOT NULL,
  MINIMUM_ORDER_QUANTITY_COUNT INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT (
  RENTAL_TERM_VIOLATION_PENALTY_AMOUNT INTEGER,
  EVERGREEN_CONTRACT_ESTIMATED_MONTH_COUNT INTEGER,
  ID VARCHAR(36) UNIQUE NOT NULL,
  EVERGREEN_CONTRACT_ESTIMATED_CHARGE_AMOUNT INTEGER,
  SERVICE_PERIOD_UO_M VARCHAR(500),
  SERVICE_PERIOD_COUNT INTEGER,
  RENTAL_CLEANUP_FEE_AMOUNT INTEGER,
  SERVICE_TYPE VARCHAR(500) NOT NULL,
  QUANTITY_SCHEDULE_TYPE VARCHAR(500),
  DISPOSAL_TYPE VARCHAR(500),
  LONG_DESCRIPTION VARCHAR(500) NOT NULL,
  MINIMUM_ADVERTISEMENT_AMOUNT INTEGER,
  IS_BACK_ORDERED BOOLEAN NOT NULL,
  VALID_FOR_PERIOD_COUNT INTEGER,
  IS_WORKER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  ALLOW_PARTIAL_REFUND BOOLEAN,
  IS_WEIGHT_ENTRY_REQUIRED BOOLEAN NOT NULL,
  IS_QUANTITY_ENTRY_REQUIRED BOOLEAN NOT NULL,
  IS_SERIALIZED BOOLEAN NOT NULL,
  REWARD_PROGRAM_POINTS_COUNT INTEGER,
  DESCRIPTION VARCHAR(500) NOT NULL,
  REVENUE_INSTALLMENT_PERIOD VARCHAR(500),
  NAME VARCHAR(500) NOT NULL,
  IS_AUTO_PROVISIONABLE BOOLEAN NOT NULL,
  IS_COUPON_REDEMPTION_ALLOWED BOOLEAN NOT NULL,
  IS_SELLABLE_INDEPENDENTLY BOOLEAN NOT NULL,
  CAN_USE_REVENUE_SCHEDULE BOOLEAN NOT NULL,
  MANUFACTURER_NAME VARCHAR(500),
  IS_INTELLECTUAL_PROPERTY_PROTECTED BOOLEAN,
  MODEL_YEAR INTEGER,
  IS_CUSTOMER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  PRODUCT_STATUS VARCHAR(500) NOT NULL,
  BRAND_GRADE VARCHAR(500),
  QUANTITY_INSTALLMENT_COUNT INTEGER,
  REQUIRED_DEPOSIT_AMOUNT INTEGER,
  REVENUE_SCHEDULE_TYPE VARCHAR(500),
  IS_PRE_ORDERABLE BOOLEAN NOT NULL,
  REQUIRES_INVIDIDUAL_UNIT_PRICING BOOLEAN NOT NULL,
  STANDARD_WARRANTY_LENGTH_MONTH INTEGER,
  CAN_USE_QUANTITY_SCHEDULE BOOLEAN NOT NULL,
  IS_INSTALLABLE BOOLEAN NOT NULL,
  IS_RAIN_CHECK_ALLOWED BOOLEAN NOT NULL,
  MINIMUM_ADVERTISEMENT_AMOUNT_START_DATE INTEGER,
  MAXIMUM_ORDER_QUANTITY_COUNT INTEGER,
  IS_MULTIPLE_COUPONS_ALLOWED BOOLEAN NOT NULL,
  ALLOW_CUSTOMER_RETURN BOOLEAN,
  MODEL_NUMBER VARCHAR(500),
  M_SR_PAMOUNT INTEGER,
  EXTERNAL_SOURCE_RECORD VARCHAR(500),
  IS_SELLABLE BOOLEAN,
  VALID_TO_DATE DATE,
  PRICE_CHARGE_TYPE VARCHAR(500) NOT NULL,
  IS_PARTNER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  REVENUE_INSTALLMENT_COUNT INTEGER,
  PRODUCT_SK_U VARCHAR(500) NOT NULL,
  QUANTITY_INSTALLMENT_PERIOD VARCHAR(500),
  IS_MANUAL_PRICE_ENTRY_REQUIRED BOOLEAN NOT NULL,
  TYPE VARCHAR(500),
  IS_SELLABLE_WITHOUT_PRICE BOOLEAN NOT NULL,
  GL_ACCOUNT_CODE VARCHAR(500),
  IS_RETURNABLE BOOLEAN NOT NULL,
  DISPLAY_URL VARCHAR(500),
  VERSION_NUMBER VARCHAR(500),
  LOT_IDENTIFIER VARCHAR(500),
  VALID_FROM_DATE DATE,
  STOCK_LEDGER_VALUATION_AMOUNT INTEGER,
  IS_DYNAMIC_BUNDLE BOOLEAN NOT NULL,
  IS_QUALITY_VERIFICATION_REQUIRED BOOLEAN NOT NULL,
  REQUIRED_DEPOSIT_PERCENTAGE INTEGER,
  IS_FOODSTAMP_PAYMENT_ALLOWED BOOLEAN NOT NULL,
  MINIMUM_ORDER_QUANTITY_COUNT INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT (
  QUANTITY_SCHEDULE_TYPE VARCHAR(500),
  DISPOSAL_TYPE VARCHAR(500),
  LONG_DESCRIPTION VARCHAR(500) NOT NULL,
  MINIMUM_ADVERTISEMENT_AMOUNT INTEGER,
  IS_BACK_ORDERED BOOLEAN NOT NULL,
  VALID_FOR_PERIOD_COUNT INTEGER,
  IS_WORKER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  ALLOW_PARTIAL_REFUND BOOLEAN,
  IS_WEIGHT_ENTRY_REQUIRED BOOLEAN NOT NULL,
  IS_QUANTITY_ENTRY_REQUIRED BOOLEAN NOT NULL,
  IS_SERIALIZED BOOLEAN NOT NULL,
  REWARD_PROGRAM_POINTS_COUNT INTEGER,
  DESCRIPTION VARCHAR(500) NOT NULL,
  REVENUE_INSTALLMENT_PERIOD VARCHAR(500),
  ID VARCHAR(36) UNIQUE NOT NULL,
  NAME VARCHAR(500) NOT NULL,
  IS_AUTO_PROVISIONABLE BOOLEAN NOT NULL,
  IS_COUPON_REDEMPTION_ALLOWED BOOLEAN NOT NULL,
  IS_SELLABLE_INDEPENDENTLY BOOLEAN NOT NULL,
  CAN_USE_REVENUE_SCHEDULE BOOLEAN NOT NULL,
  MANUFACTURER_NAME VARCHAR(500),
  IS_INTELLECTUAL_PROPERTY_PROTECTED BOOLEAN,
  MODEL_YEAR INTEGER,
  IS_CUSTOMER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  PRODUCT_STATUS VARCHAR(500) NOT NULL,
  BRAND_GRADE VARCHAR(500),
  QUANTITY_INSTALLMENT_COUNT INTEGER,
  REQUIRED_DEPOSIT_AMOUNT INTEGER,
  REVENUE_SCHEDULE_TYPE VARCHAR(500),
  IS_PRE_ORDERABLE BOOLEAN NOT NULL,
  REQUIRES_INVIDIDUAL_UNIT_PRICING BOOLEAN NOT NULL,
  STANDARD_WARRANTY_LENGTH_MONTH INTEGER,
  CAN_USE_QUANTITY_SCHEDULE BOOLEAN NOT NULL,
  IS_INSTALLABLE BOOLEAN NOT NULL,
  IS_RAIN_CHECK_ALLOWED BOOLEAN NOT NULL,
  MINIMUM_ADVERTISEMENT_AMOUNT_START_DATE INTEGER,
  MAXIMUM_ORDER_QUANTITY_COUNT INTEGER,
  IS_MULTIPLE_COUPONS_ALLOWED BOOLEAN NOT NULL,
  ALLOW_CUSTOMER_RETURN BOOLEAN,
  MODEL_NUMBER VARCHAR(500),
  M_SR_PAMOUNT INTEGER,
  EXTERNAL_SOURCE_RECORD VARCHAR(500),
  IS_SELLABLE BOOLEAN,
  VALID_TO_DATE DATE,
  PRICE_CHARGE_TYPE VARCHAR(500) NOT NULL,
  IS_PARTNER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  REVENUE_INSTALLMENT_COUNT INTEGER,
  PRODUCT_SK_U VARCHAR(500) NOT NULL,
  QUANTITY_INSTALLMENT_PERIOD VARCHAR(500),
  IS_MANUAL_PRICE_ENTRY_REQUIRED BOOLEAN NOT NULL,
  TYPE VARCHAR(500),
  IS_SELLABLE_WITHOUT_PRICE BOOLEAN NOT NULL,
  GL_ACCOUNT_CODE VARCHAR(500),
  IS_RETURNABLE BOOLEAN NOT NULL,
  DISPLAY_URL VARCHAR(500),
  VERSION_NUMBER VARCHAR(500),
  LOT_IDENTIFIER VARCHAR(500),
  VALID_FROM_DATE DATE,
  STOCK_LEDGER_VALUATION_AMOUNT INTEGER,
  IS_DYNAMIC_BUNDLE BOOLEAN NOT NULL,
  IS_QUALITY_VERIFICATION_REQUIRED BOOLEAN NOT NULL,
  REQUIRED_DEPOSIT_PERCENTAGE INTEGER,
  IS_FOODSTAMP_PAYMENT_ALLOWED BOOLEAN NOT NULL,
  MINIMUM_ORDER_QUANTITY_COUNT INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.BRAND (
  ID VARCHAR(36) UNIQUE NOT NULL,
  BRAND_GRADE VARCHAR(500) NOT NULL,
  NAME VARCHAR(500) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.BUNDLE_PRODUCT (
  EXPECTED_WASTE_COUNT INTEGER,
  QUANTITY_COUNT INTEGER,
  ID VARCHAR(36) UNIQUE NOT NULL,
  TARE_WEIGHT INTEGER,
  BUNDLED_PRODUCTS_SUBSTITUTIONAL BOOLEAN NOT NULL,
  BUNDLED_PRODUCTS_DECIDED_AT_USE BOOLEAN,
  BUNDLED_PRODUCTS_DECIDES_AVAILABILITY BOOLEAN,
  BUNDLED_PRODUCTS_SOLD_TOGETHER BOOLEAN NOT NULL,
  WEIGHT_UO_M VARCHAR(500),
  QUANTITY_UNIT_OF_MEASURE VARCHAR(500),
  QUANTITY_SCHEDULE_TYPE VARCHAR(500),
  DISPOSAL_TYPE VARCHAR(500),
  LONG_DESCRIPTION VARCHAR(500) NOT NULL,
  MINIMUM_ADVERTISEMENT_AMOUNT INTEGER,
  IS_BACK_ORDERED BOOLEAN NOT NULL,
  VALID_FOR_PERIOD_COUNT INTEGER,
  IS_WORKER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  ALLOW_PARTIAL_REFUND BOOLEAN,
  IS_WEIGHT_ENTRY_REQUIRED BOOLEAN NOT NULL,
  IS_QUANTITY_ENTRY_REQUIRED BOOLEAN NOT NULL,
  IS_SERIALIZED BOOLEAN NOT NULL,
  REWARD_PROGRAM_POINTS_COUNT INTEGER,
  DESCRIPTION VARCHAR(500) NOT NULL,
  REVENUE_INSTALLMENT_PERIOD VARCHAR(500),
  NAME VARCHAR(500) NOT NULL,
  IS_AUTO_PROVISIONABLE BOOLEAN NOT NULL,
  IS_COUPON_REDEMPTION_ALLOWED BOOLEAN NOT NULL,
  IS_SELLABLE_INDEPENDENTLY BOOLEAN NOT NULL,
  CAN_USE_REVENUE_SCHEDULE BOOLEAN NOT NULL,
  MANUFACTURER_NAME VARCHAR(500),
  IS_INTELLECTUAL_PROPERTY_PROTECTED BOOLEAN,
  MODEL_YEAR INTEGER,
  IS_CUSTOMER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  PRODUCT_STATUS VARCHAR(500) NOT NULL,
  BRAND_GRADE VARCHAR(500),
  QUANTITY_INSTALLMENT_COUNT INTEGER,
  REQUIRED_DEPOSIT_AMOUNT INTEGER,
  REVENUE_SCHEDULE_TYPE VARCHAR(500),
  IS_PRE_ORDERABLE BOOLEAN NOT NULL,
  REQUIRES_INVIDIDUAL_UNIT_PRICING BOOLEAN NOT NULL,
  STANDARD_WARRANTY_LENGTH_MONTH INTEGER,
  CAN_USE_QUANTITY_SCHEDULE BOOLEAN NOT NULL,
  IS_INSTALLABLE BOOLEAN NOT NULL,
  IS_RAIN_CHECK_ALLOWED BOOLEAN NOT NULL,
  MINIMUM_ADVERTISEMENT_AMOUNT_START_DATE INTEGER,
  MAXIMUM_ORDER_QUANTITY_COUNT INTEGER,
  IS_MULTIPLE_COUPONS_ALLOWED BOOLEAN NOT NULL,
  ALLOW_CUSTOMER_RETURN BOOLEAN,
  MODEL_NUMBER VARCHAR(500),
  M_SR_PAMOUNT INTEGER,
  EXTERNAL_SOURCE_RECORD VARCHAR(500),
  IS_SELLABLE BOOLEAN,
  VALID_TO_DATE DATE,
  PRICE_CHARGE_TYPE VARCHAR(500) NOT NULL,
  IS_PARTNER_DISCOUNT_ALLOWED BOOLEAN NOT NULL,
  REVENUE_INSTALLMENT_COUNT INTEGER,
  PRODUCT_SK_U VARCHAR(500) NOT NULL,
  QUANTITY_INSTALLMENT_PERIOD VARCHAR(500),
  IS_MANUAL_PRICE_ENTRY_REQUIRED BOOLEAN NOT NULL,
  TYPE VARCHAR(500),
  IS_SELLABLE_WITHOUT_PRICE BOOLEAN NOT NULL,
  GL_ACCOUNT_CODE VARCHAR(500),
  IS_RETURNABLE BOOLEAN NOT NULL,
  DISPLAY_URL VARCHAR(500),
  VERSION_NUMBER VARCHAR(500),
  LOT_IDENTIFIER VARCHAR(500),
  VALID_FROM_DATE DATE,
  STOCK_LEDGER_VALUATION_AMOUNT INTEGER,
  IS_DYNAMIC_BUNDLE BOOLEAN NOT NULL,
  IS_QUALITY_VERIFICATION_REQUIRED BOOLEAN NOT NULL,
  REQUIRED_DEPOSIT_PERCENTAGE INTEGER,
  IS_FOODSTAMP_PAYMENT_ALLOWED BOOLEAN NOT NULL,
  MINIMUM_ORDER_QUANTITY_COUNT INTEGER,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_RELATED_PRODUCT_SALES_ORDER_PRODUCT1_JOIN (
  PRODUCT_RELATED_PRODUCT_ID  VARCHAR(36) NOT NULL,
  SALES_ORDER_PRODUCT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_RELATED_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT_RELATED_PRODUCT(ID),
  FOREIGN KEY(SALES_ORDER_PRODUCT_ID) REFERENCES SALES_ORDER_ENTITY_GROUP.SALES_ORDER_PRODUCT(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_RELATED_PRODUCT_PARENT_PRODUCT_JOIN (
  PRODUCT_RELATED_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_RELATED_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT_RELATED_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_RELATED_PRODUCT_CHILD_PRODUCT_JOIN (
  PRODUCT_RELATED_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_RELATED_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT_RELATED_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_RELATED_PRODUCT_PRODUCT_RELATIONSHIP_TYPE_JOIN (
  PRODUCT_RELATED_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_RELATIONSHIP_TYPE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_RELATED_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT_RELATED_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_RELATIONSHIP_TYPE_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT_RELATIONSHIP_TYPE(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_RELATED_PRODUCT_SALES_ORDER_PRODUCT2_JOIN (
  PRODUCT_RELATED_PRODUCT_ID  VARCHAR(36) NOT NULL,
  SALES_ORDER_PRODUCT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_RELATED_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT_RELATED_PRODUCT(ID),
  FOREIGN KEY(SALES_ORDER_PRODUCT_ID) REFERENCES SALES_ORDER_ENTITY_GROUP.SALES_ORDER_PRODUCT(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_TRANSLATION_PRODUCT_JOIN (
  PRODUCT_TRANSLATION_ID  VARCHAR(36) NOT NULL,
  PRODUCT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_TRANSLATION_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT_TRANSLATION(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_IMAGE_PRODUCT_JOIN (
  PRODUCT_IMAGE_ID  VARCHAR(36) NOT NULL,
  PRODUCT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_IMAGE_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT_IMAGE(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_IMAGE_TRANSLATION_PRODUCT_IMAGE_JOIN (
  PRODUCT_IMAGE_TRANSLATION_ID  VARCHAR(36) NOT NULL,
  PRODUCT_IMAGE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_IMAGE_TRANSLATION_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT_IMAGE_TRANSLATION(ID),
  FOREIGN KEY(PRODUCT_IMAGE_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT_IMAGE(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.GOODS_PRODUCT_PRIMARY_PRODUCT_CATEGORY_JOIN (
  GOODS_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_CATEGORY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(GOODS_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.GOODS_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.GOODS_PRODUCT_MASTER_PRODUCT_JOIN (
  GOODS_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(GOODS_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.GOODS_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.GOODS_PRODUCT_PRIMARY_SALES_CHANNEL_JOIN (
  GOODS_PRODUCT_ID  VARCHAR(36) NOT NULL,
  SALES_CHANNEL_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(GOODS_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.GOODS_PRODUCT(ID),
  FOREIGN KEY(SALES_CHANNEL_ID) REFERENCES SALES_ORDER_ENTITY_GROUP.SALES_CHANNEL(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.GOODS_PRODUCT_VALID_FOR_PERIOD_UO_M_JOIN (
  GOODS_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_VALIDITY_TIME_PERIOD_UO_M_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(GOODS_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.GOODS_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_VALIDITY_TIME_PERIOD_UO_M_ID) REFERENCES PRODUCT_ATTRIBUTE_ENTITY_GROUP.PRODUCT_VALIDITY_TIME_PERIOD_UO_M(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.GOODS_PRODUCT_BRAND_JOIN (
  GOODS_PRODUCT_ID  VARCHAR(36) NOT NULL,
  BRAND_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(GOODS_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.GOODS_PRODUCT(ID),
  FOREIGN KEY(BRAND_ID) REFERENCES PRODUCT_ENTITY_GROUP.BRAND(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT_SERVICE_PROVIDER_ACCOUNT_JOIN (
  SERVICE_PRODUCT_ID  VARCHAR(36) NOT NULL,
  ACCOUNT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(SERVICE_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT(ID),
  FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT_ENTITY_GROUP.ACCOUNT(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT_PRIMARY_PRODUCT_CATEGORY_JOIN (
  SERVICE_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_CATEGORY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(SERVICE_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT_MASTER_PRODUCT_JOIN (
  SERVICE_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(SERVICE_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT_PRIMARY_SALES_CHANNEL_JOIN (
  SERVICE_PRODUCT_ID  VARCHAR(36) NOT NULL,
  SALES_CHANNEL_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(SERVICE_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT(ID),
  FOREIGN KEY(SALES_CHANNEL_ID) REFERENCES SALES_ORDER_ENTITY_GROUP.SALES_CHANNEL(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT_VALID_FOR_PERIOD_UO_M_JOIN (
  SERVICE_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_VALIDITY_TIME_PERIOD_UO_M_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(SERVICE_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_VALIDITY_TIME_PERIOD_UO_M_ID) REFERENCES PRODUCT_ATTRIBUTE_ENTITY_GROUP.PRODUCT_VALIDITY_TIME_PERIOD_UO_M(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT_BRAND_JOIN (
  SERVICE_PRODUCT_ID  VARCHAR(36) NOT NULL,
  BRAND_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(SERVICE_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.SERVICE_PRODUCT(ID),
  FOREIGN KEY(BRAND_ID) REFERENCES PRODUCT_ENTITY_GROUP.BRAND(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_PRIMARY_PRODUCT_CATEGORY_JOIN (
  PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_CATEGORY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID),
  FOREIGN KEY(PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_MASTER_PRODUCT_JOIN (
  PRODUCT_ID_LEFT  VARCHAR(36) NOT NULL,
  PRODUCT_ID_RIGHT VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_ID_LEFT) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID),
  FOREIGN KEY(PRODUCT_ID_RIGHT) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_PRIMARY_SALES_CHANNEL_JOIN (
  PRODUCT_ID  VARCHAR(36) NOT NULL,
  SALES_CHANNEL_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID),
  FOREIGN KEY(SALES_CHANNEL_ID) REFERENCES SALES_ORDER_ENTITY_GROUP.SALES_CHANNEL(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_VALID_FOR_PERIOD_UO_M_JOIN (
  PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_VALIDITY_TIME_PERIOD_UO_M_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID),
  FOREIGN KEY(PRODUCT_VALIDITY_TIME_PERIOD_UO_M_ID) REFERENCES PRODUCT_ATTRIBUTE_ENTITY_GROUP.PRODUCT_VALIDITY_TIME_PERIOD_UO_M(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.PRODUCT_BRAND_JOIN (
  PRODUCT_ID  VARCHAR(36) NOT NULL,
  BRAND_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID),
  FOREIGN KEY(BRAND_ID) REFERENCES PRODUCT_ENTITY_GROUP.BRAND(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.BUNDLE_PRODUCT_PRIMARY_PRODUCT_CATEGORY_JOIN (
  BUNDLE_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_CATEGORY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(BUNDLE_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.BUNDLE_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.BUNDLE_PRODUCT_MASTER_PRODUCT_JOIN (
  BUNDLE_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(BUNDLE_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.BUNDLE_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.BUNDLE_PRODUCT_PRIMARY_SALES_CHANNEL_JOIN (
  BUNDLE_PRODUCT_ID  VARCHAR(36) NOT NULL,
  SALES_CHANNEL_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(BUNDLE_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.BUNDLE_PRODUCT(ID),
  FOREIGN KEY(SALES_CHANNEL_ID) REFERENCES SALES_ORDER_ENTITY_GROUP.SALES_CHANNEL(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.BUNDLE_PRODUCT_VALID_FOR_PERIOD_UO_M_JOIN (
  BUNDLE_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_VALIDITY_TIME_PERIOD_UO_M_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(BUNDLE_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.BUNDLE_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_VALIDITY_TIME_PERIOD_UO_M_ID) REFERENCES PRODUCT_ATTRIBUTE_ENTITY_GROUP.PRODUCT_VALIDITY_TIME_PERIOD_UO_M(ID)
);

CREATE TABLE PRODUCT_ENTITY_GROUP.BUNDLE_PRODUCT_BRAND_JOIN (
  BUNDLE_PRODUCT_ID  VARCHAR(36) NOT NULL,
  BRAND_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(BUNDLE_PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.BUNDLE_PRODUCT(ID),
  FOREIGN KEY(BRAND_ID) REFERENCES PRODUCT_ENTITY_GROUP.BRAND(ID)
);