#%RAML 1.0 Library
types:
  BillingFrequency:
    properties:
      id:
        type: string
      billingFrequencyName:
        type: string
      name:
        type: string
  AccountContactRole:
    properties:
      accountContactRoleType?:
        type: string
      id:
        type: string
      activeFromDate?:
        type: date-only
      activeToDate?:
        type: date-only
      accountContact?:
        items: AccountContact
  AccountContact:
    properties:
      reportsToAccountContact?:
        items: AccountContact
      mailingAddress?:
        items: contactpoint_eg.ContactPointAddress
      account:
        items: Account
      faxPhone?:
        items: contactpoint_eg.ContactPointPhone
      id:
        type: string
      departmentName?:
        type: string
      businessPhone?:
        items: contactpoint_eg.ContactPointPhone
      contactEmail?:
        items: contactpoint_eg.ContactPointEmail
      mobilePhone?:
        items: contactpoint_eg.ContactPointPhone
      assistantPhone?:
        type: string
      indirectRelationAccountContact?:
        items: AccountContact
      title?:
        type: string
      lastActivityDate?:
        type: date-only
      contactNote?:
        type: string
      assistantName?:
        type: string
      individual:
        items: party_eg.Individual
      otherContactAddress?:
        items: contactpoint_eg.ContactPointAddress
      homePhone?:
        items: contactpoint_eg.ContactPointPhone
  AccountPartner:
    properties:
      account:
        items: Account
      id:
        type: string
      partnerAccount:
        items: Account
  Account:
    properties:
      billDeliveryMethod?:
        type: string
      billContactAddress?:
        items: contactpoint_eg.ContactPointAddress
      useAsSalesAccount:
        type: boolean
      assignTerritoryFlag?:
        type: boolean
      billFrequency?:
        items: BillingFrequency
      autoPayEnabledFlag?:
        type: boolean
      autoPaymentAmount?:
        type: integer
      useAsServiceAccount:
        type: boolean
      useAsBillingAccount:
        type: boolean
      partyRole?:
        items: partyrole_eg.PartyRole
      faxPhone?:
        items: contactpoint_eg.ContactPointPhone
      description?:
        type: string
      salesPhone?:
        items: contactpoint_eg.ContactPointPhone
      id:
        type: string
      sLAExpirationDate?:
        type: date-only
      name:
        type: string
      accountType?:
        type: string
      autoPaymentMethod?:
        items: paymentmethod_eg.PaymentMethod
      balanceAmount?:
        type: integer
      holdStatusReason?:
        type: string
      generalLedgerAccount?:
        type: string
      thirtyDayBalanceAmount?:
        type: integer
      sixtyDayBalanceAmount?:
        type: integer
      useAsShippingAccount:
        type: boolean
      shippingAddress?:
        items: contactpoint_eg.ContactPointAddress
      party?:
        items: party_eg.Party
      parentAccount?:
        items: Account
      sLAType?:
        type: string
      shippingContact?:
        items: AccountContact
      balanceAmountLimit?:
        type: integer
      shippingPhoneid?:
        items: contactpoint_eg.ContactPointPhone
      shippingEmail?:
        items: contactpoint_eg.ContactPointEmail
      lastActivityDate?:
        type: date-only
      orderDeliveryMethod?:
        items: salesorder_eg.OrderDeliveryMethod
      primarySalesContactPoint?:
        items: contactpoint_eg.ContactPoint
      number:
        type: string
      ninetyDayBalanceAmount?:
        type: integer
      paymentTerm:
        type: string
      defaultFreightTerms?:
        type: string
uses:
  contactpoint_eg: ../ContactPoint/schema.yaml
  party_eg: ../Party/schema.yaml
  salesorder_eg: ../../SalesOrder/SalesOrder/schema.yaml
  paymentmethod_eg: ../../PaymentMethod/PaymentMethod/schema.yaml
  partyrole_eg: ../PartyRole/schema.yaml
