#%RAML 1.0 Library
types:
  Supplier:
    type: PartyRole
    properties:
      satisfactionEthicsRank?:
        type: integer
      contractInvoiceAccuracyRate?:
        type: integer
      satisfactionWeightPercent?:
        type: integer
      contractOnTimeDeliveryRate?:
        type: integer
      id:
        type: string
      activeFromDate:
        type: date-only
      activeToDate?:
        type: date-only
      competitiveWarrantyRank?:
        type: integer
      competitiveMarketingRank?:
        type: integer
      contractDeliveryCorrectnessRate?:
        type: integer
      competitiveWeightScore?:
        type: integer
      contractSLAIssueRate?:
        type: integer
      competitiveWeightPercent?:
        type: integer
      supplierScore?:
        type: integer
      competitiveProductPriceRank?:
        type: integer
      contractWeightPercent?:
        type: integer
      supplierSpend?:
        type: integer
      satisfactionTechnicalSupportRank?:
        type: integer
      contractWeightScore?:
        type: integer
      satisfactionCustomerServiceRank?:
        type: integer
      satisfactionWeightScore?:
        type: integer
      contractSourcingCycleDays?:
        type: integer
      supplierType?:
        type: string
      isCarrier?:
        type: boolean
      contractProductReturnRate?:
        type: integer
      competitiveCostAvoidanceRank?:
        type: integer
      contractProductQualityRate?:
        type: integer
      contractBudgetCostRate?:
        type: integer
  CustomerStatusHistory:
    properties:
      startDateTime:
        type: time-only
      partyRole:
        items: PartyRole
      partyRoleStatus:
        type: string
      id:
        type: string
      endDateTIme:
        type: time-only
  Competitor:
    type: PartyRole
    properties:
      competitorStrengths?:
        type: string
      competitorFromDate:
        type: date-only
      socialMediaPostRate?:
        type: integer
      competitorThreats?:
        type: string
      currentRatio?:
        type: integer
      cashFlowGrowth?:
        type: integer
      competitorObjectives?:
        type: string
      netProfitMargin?:
        type: integer
      id:
        type: string
      competitorWeaknesses?:
        type: string
      pressMentionsRate?:
        type: integer
      assetTurnoverRatio?:
        type: integer
      competitorToDate?:
        type: date-only
      competitorLeverageOpportunities?:
        type: string
      assetReturnRatio?:
        type: integer
      ptoENumber?:
        type: integer
      adKeywords?:
        type: string
      adReachRate?:
        type: integer
  Seller:
    type: PartyRole
    properties:
      communityParticipationCount?:
        type: integer
      demonstrationsGivenCount?:
        type: integer
      eventParticipationCount?:
        type: integer
      customerSatisfactionScore?:
        type: integer
      trainingCertificationCount?:
        type: integer
      opportunityInvolvementCount?:
        type: integer
      marketingDevelopmentAmount?:
        type: integer
      sellerType?:
        type: string
      documentationDownloadCount?:
        type: integer
      id:
        type: string
      activeFromDate:
        type: date-only
      activeToDate?:
        type: date-only
      trialParticipationCount?:
        type: integer
      creditRating?:
        type: integer
      satisfactionScore?:
        type: integer
      salesAmount?:
        type: integer
      opportunityWinRate?:
        type: integer
      productReturnRate?:
        type: integer
      leadGenerationCount?:
        type: integer
      inventoryValueAmount?:
        type: integer
      majorPostSaleSupportNeeded?:
        type: boolean
      trainingParticipationCount?:
        type: integer
      newCustomerAcquisitionCount?:
        type: integer
      successStoryCount?:
        type: integer
      systemLoginCount?:
        type: integer
      jointBusinessPlanExist?:
        type: boolean
      averageConvertedLeadAmount?:
        type: integer
      estimatedPartnerGrossMargin?:
        type: integer
  Customer:
    type: PartyRole
    properties:
      customerStatus:
        type: string
      prospectRating?:
        type: string
      netPromoterScore?:
        type: integer
      customerSatisfactionScore?:
        type: integer
      id:
        type: string
      marketingEmailResponseRate?:
        type: integer
      totalContractedAmount?:
        type: integer
      totalProfitContributionAmount?:
        type: integer
      customerNumber?:
        type: string
      churnScore?:
        type: integer
      originatingCustomerSource?:
        type: string
      totalLifeTimeValue?:
        type: integer
      totalBookingsAmount?:
        type: integer
      last24MonthsNewRevenueAmount?:
        type: integer
      last12MonthsNewRevenueAmount?:
        type: integer
      last12MonthsSupportCallCount?:
        type: integer
  PartyRole:
    properties:
      id:
        type: string
      party:
        items: party_eg.Party
uses:
  party_eg: ../Party/schema.yaml
