CREATE SCHEMA IF NOT EXISTS CONTACT_POINT_ENTITY_GROUP;

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_TYPE (
  OPT_IN_PRIORITY INTEGER NOT NULL,
  ID VARCHAR(36) UNIQUE NOT NULL,
  NAME VARCHAR(500) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_LOCATION (
  ID VARCHAR(36) UNIQUE NOT NULL,
  PRIMARY_FLAG BOOLEAN,
  BEST_TIME_TO_CONTACT_START_TIME TIME,
  PROFILE_LAST_UPDATED_DATE TIME,
  PARTY_ROLE VARCHAR(500),
  ACTIVE_FROM_DATE DATE NOT NULL,
  ACTIVE_TO_DATE DATE,
  PROFILE_OCCURRENCE_COUNT INTEGER,
  PROFILE_FIRST_CREATED_DATE TIME,
  BEST_TIME_TO_CONTACT_END_TIME TIME,
  FOR_BUSINESS_USE BOOLEAN NOT NULL,
  FOR_PERSONAL_USE BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_APP (
  APPLICATION_LOGIN VARCHAR(500),
  ID VARCHAR(36) UNIQUE NOT NULL,
  PRIMARY_FLAG BOOLEAN,
  BEST_TIME_TO_CONTACT_START_TIME TIME,
  PROFILE_LAST_UPDATED_DATE TIME,
  PARTY_ROLE VARCHAR(500),
  ACTIVE_FROM_DATE DATE NOT NULL,
  ACTIVE_TO_DATE DATE,
  PROFILE_OCCURRENCE_COUNT INTEGER,
  PROFILE_FIRST_CREATED_DATE TIME,
  BEST_TIME_TO_CONTACT_END_TIME TIME,
  FOR_BUSINESS_USE BOOLEAN NOT NULL,
  FOR_PERSONAL_USE BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_ADDRESS (
  IS_USED_FOR_SHIPPING BOOLEAN,
  STATE_PROVINCE_NAME VARCHAR(500),
  ADDRESS_LINE3 VARCHAR(500),
  COUNTRY_NAME VARCHAR(500),
  POSTAL_CODE_TEXT VARCHAR(500),
  ID VARCHAR(36) UNIQUE NOT NULL,
  GEO_LATITUDE INTEGER,
  ADDRESS_LINE2 VARCHAR(500),
  ADDRESS_LINE4 VARCHAR(500),
  GEO_ACCURACY INTEGER,
  GEO_LONGITUDE INTEGER,
  ADDRESS_LINE1 VARCHAR(500),
  CITY_NAME VARCHAR(500),
  IS_USED_FOR_BILLING BOOLEAN,
  PRIMARY_FLAG BOOLEAN,
  BEST_TIME_TO_CONTACT_START_TIME TIME,
  PROFILE_LAST_UPDATED_DATE TIME,
  PARTY_ROLE VARCHAR(500),
  ACTIVE_FROM_DATE DATE NOT NULL,
  ACTIVE_TO_DATE DATE,
  PROFILE_OCCURRENCE_COUNT INTEGER,
  PROFILE_FIRST_CREATED_DATE TIME,
  BEST_TIME_TO_CONTACT_END_TIME TIME,
  FOR_BUSINESS_USE BOOLEAN NOT NULL,
  FOR_PERSONAL_USE BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.PARTY_WEB_ADDRESS (
  ID VARCHAR(36) UNIQUE NOT NULL,
  WEB_SITE_UR_L VARCHAR(500) NOT NULL,
  PRIMARY_FLAG BOOLEAN,
  BEST_TIME_TO_CONTACT_START_TIME TIME,
  PROFILE_LAST_UPDATED_DATE TIME,
  PARTY_ROLE VARCHAR(500),
  ACTIVE_FROM_DATE DATE NOT NULL,
  ACTIVE_TO_DATE DATE,
  PROFILE_OCCURRENCE_COUNT INTEGER,
  PROFILE_FIRST_CREATED_DATE TIME,
  BEST_TIME_TO_CONTACT_END_TIME TIME,
  FOR_BUSINESS_USE BOOLEAN NOT NULL,
  FOR_PERSONAL_USE BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_EMAIL (
  EMAIL_LATEST_BOUNCE_REASON_TEXT VARCHAR(500) NOT NULL,
  ID VARCHAR(36) UNIQUE NOT NULL,
  EMAIL_MAIL_BOX VARCHAR(500) NOT NULL,
  EMAIL_DOMAIN VARCHAR(500) NOT NULL,
  EMAIL_ADDRESS VARCHAR(500) NOT NULL,
  EMAIL_LATEST_BOUNCE_DATE_TIME DATE NOT NULL,
  PRIMARY_FLAG BOOLEAN,
  BEST_TIME_TO_CONTACT_START_TIME TIME,
  PROFILE_LAST_UPDATED_DATE TIME,
  PARTY_ROLE VARCHAR(500),
  ACTIVE_FROM_DATE DATE NOT NULL,
  ACTIVE_TO_DATE DATE,
  PROFILE_OCCURRENCE_COUNT INTEGER,
  PROFILE_FIRST_CREATED_DATE TIME,
  BEST_TIME_TO_CONTACT_END_TIME TIME,
  FOR_BUSINESS_USE BOOLEAN NOT NULL,
  FOR_PERSONAL_USE BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_SOCIAL (
  ID VARCHAR(36) UNIQUE NOT NULL,
  PROFILE_PICTURE_UR_L VARCHAR(500) NOT NULL,
  FOLLOWERS_COUNT INTEGER NOT NULL,
  SOCIAL_HANDLE_NAME VARCHAR(500) NOT NULL,
  SOCIAL_FAN_STATUS VARCHAR(500) NOT NULL,
  SOCIAL_HANDLE VARCHAR(500) NOT NULL,
  SOCIAL_NETWORK_PROVIDER VARCHAR(500) NOT NULL,
  PRIMARY_FLAG BOOLEAN,
  BEST_TIME_TO_CONTACT_START_TIME TIME,
  PROFILE_LAST_UPDATED_DATE TIME,
  PARTY_ROLE VARCHAR(500),
  ACTIVE_FROM_DATE DATE NOT NULL,
  ACTIVE_TO_DATE DATE,
  PROFILE_OCCURRENCE_COUNT INTEGER,
  PROFILE_FIRST_CREATED_DATE TIME,
  BEST_TIME_TO_CONTACT_END_TIME TIME,
  FOR_BUSINESS_USE BOOLEAN NOT NULL,
  FOR_PERSONAL_USE BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_PHONE (
  EXTENSION_NUMBER VARCHAR(500),
  PHONE_COUNTRY_CODE VARCHAR(500),
  COUNTRY_NAME VARCHAR(500),
  ID VARCHAR(36) UNIQUE NOT NULL,
  AREA_CODE VARCHAR(500),
  IS_SM_SCAPABLE BOOLEAN NOT NULL,
  SHORT_CODE INTEGER,
  FORMATTED_INTERNATIONAL_PHONE_NUMBER VARCHAR(500) NOT NULL,
  PRIMARY_PHONE_TYPE VARCHAR(500) NOT NULL,
  IS_FAX_CAPABLE BOOLEAN NOT NULL,
  FORMATTED_E164_PHONE_NUMBER VARCHAR(500),
  FORMATTED_NATIONAL_PHONE_NUMBER VARCHAR(500) NOT NULL,
  TELEPHONE_NUMBER VARCHAR(500) NOT NULL,
  PRIMARY_FLAG BOOLEAN,
  BEST_TIME_TO_CONTACT_START_TIME TIME,
  PROFILE_LAST_UPDATED_DATE TIME,
  PARTY_ROLE VARCHAR(500),
  ACTIVE_FROM_DATE DATE NOT NULL,
  ACTIVE_TO_DATE DATE,
  PROFILE_OCCURRENCE_COUNT INTEGER,
  PROFILE_FIRST_CREATED_DATE TIME,
  BEST_TIME_TO_CONTACT_END_TIME TIME,
  FOR_BUSINESS_USE BOOLEAN NOT NULL,
  FOR_PERSONAL_USE BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT (
  PRIMARY_FLAG BOOLEAN,
  BEST_TIME_TO_CONTACT_START_TIME TIME,
  PROFILE_LAST_UPDATED_DATE TIME,
  PARTY_ROLE VARCHAR(500),
  ID VARCHAR(36) UNIQUE NOT NULL,
  ACTIVE_FROM_DATE DATE NOT NULL,
  ACTIVE_TO_DATE DATE,
  PROFILE_OCCURRENCE_COUNT INTEGER,
  PROFILE_FIRST_CREATED_DATE TIME,
  BEST_TIME_TO_CONTACT_END_TIME TIME,
  FOR_BUSINESS_USE BOOLEAN NOT NULL,
  FOR_PERSONAL_USE BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_LOCATION_PARTY_JOIN (
  CONTACT_POINT_LOCATION_ID  VARCHAR(36) NOT NULL,
  PARTY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_LOCATION_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_LOCATION(ID),
  FOREIGN KEY(PARTY_ID) REFERENCES PARTY_ENTITY_GROUP.PARTY(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_LOCATION_CONTACT_POINT_TYPE_JOIN (
  CONTACT_POINT_LOCATION_ID  VARCHAR(36) NOT NULL,
  CONTACT_POINT_TYPE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_LOCATION_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_LOCATION(ID),
  FOREIGN KEY(CONTACT_POINT_TYPE_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_TYPE(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_APP_PARTY_JOIN (
  CONTACT_POINT_APP_ID  VARCHAR(36) NOT NULL,
  PARTY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_APP_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_APP(ID),
  FOREIGN KEY(PARTY_ID) REFERENCES PARTY_ENTITY_GROUP.PARTY(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_APP_CONTACT_POINT_TYPE_JOIN (
  CONTACT_POINT_APP_ID  VARCHAR(36) NOT NULL,
  CONTACT_POINT_TYPE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_APP_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_APP(ID),
  FOREIGN KEY(CONTACT_POINT_TYPE_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_TYPE(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_ADDRESS_CONTACT_PHONE_JOIN (
  CONTACT_POINT_ADDRESS_ID  VARCHAR(36) NOT NULL,
  CONTACT_POINT_PHONE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_ADDRESS_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_ADDRESS(ID),
  FOREIGN KEY(CONTACT_POINT_PHONE_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_PHONE(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_ADDRESS_PARTY_JOIN (
  CONTACT_POINT_ADDRESS_ID  VARCHAR(36) NOT NULL,
  PARTY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_ADDRESS_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_ADDRESS(ID),
  FOREIGN KEY(PARTY_ID) REFERENCES PARTY_ENTITY_GROUP.PARTY(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_ADDRESS_CONTACT_POINT_TYPE_JOIN (
  CONTACT_POINT_ADDRESS_ID  VARCHAR(36) NOT NULL,
  CONTACT_POINT_TYPE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_ADDRESS_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_ADDRESS(ID),
  FOREIGN KEY(CONTACT_POINT_TYPE_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_TYPE(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.PARTY_WEB_ADDRESS_PARTY_JOIN (
  PARTY_WEB_ADDRESS_ID  VARCHAR(36) NOT NULL,
  PARTY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PARTY_WEB_ADDRESS_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.PARTY_WEB_ADDRESS(ID),
  FOREIGN KEY(PARTY_ID) REFERENCES PARTY_ENTITY_GROUP.PARTY(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.PARTY_WEB_ADDRESS_CONTACT_POINT_TYPE_JOIN (
  PARTY_WEB_ADDRESS_ID  VARCHAR(36) NOT NULL,
  CONTACT_POINT_TYPE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PARTY_WEB_ADDRESS_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.PARTY_WEB_ADDRESS(ID),
  FOREIGN KEY(CONTACT_POINT_TYPE_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_TYPE(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_EMAIL_PARTY_JOIN (
  CONTACT_POINT_EMAIL_ID  VARCHAR(36) NOT NULL,
  PARTY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_EMAIL_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_EMAIL(ID),
  FOREIGN KEY(PARTY_ID) REFERENCES PARTY_ENTITY_GROUP.PARTY(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_EMAIL_CONTACT_POINT_TYPE_JOIN (
  CONTACT_POINT_EMAIL_ID  VARCHAR(36) NOT NULL,
  CONTACT_POINT_TYPE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_EMAIL_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_EMAIL(ID),
  FOREIGN KEY(CONTACT_POINT_TYPE_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_TYPE(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_SOCIAL_PARTY_JOIN (
  CONTACT_POINT_SOCIAL_ID  VARCHAR(36) NOT NULL,
  PARTY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_SOCIAL_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_SOCIAL(ID),
  FOREIGN KEY(PARTY_ID) REFERENCES PARTY_ENTITY_GROUP.PARTY(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_SOCIAL_CONTACT_POINT_TYPE_JOIN (
  CONTACT_POINT_SOCIAL_ID  VARCHAR(36) NOT NULL,
  CONTACT_POINT_TYPE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_SOCIAL_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_SOCIAL(ID),
  FOREIGN KEY(CONTACT_POINT_TYPE_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_TYPE(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_PHONE_PARTY_JOIN (
  CONTACT_POINT_PHONE_ID  VARCHAR(36) NOT NULL,
  PARTY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_PHONE_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_PHONE(ID),
  FOREIGN KEY(PARTY_ID) REFERENCES PARTY_ENTITY_GROUP.PARTY(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_PHONE_CONTACT_POINT_TYPE_JOIN (
  CONTACT_POINT_PHONE_ID  VARCHAR(36) NOT NULL,
  CONTACT_POINT_TYPE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_PHONE_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_PHONE(ID),
  FOREIGN KEY(CONTACT_POINT_TYPE_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_TYPE(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_PARTY_JOIN (
  CONTACT_POINT_ID  VARCHAR(36) NOT NULL,
  PARTY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT(ID),
  FOREIGN KEY(PARTY_ID) REFERENCES PARTY_ENTITY_GROUP.PARTY(ID)
);

CREATE TABLE CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_CONTACT_POINT_TYPE_JOIN (
  CONTACT_POINT_ID  VARCHAR(36) NOT NULL,
  CONTACT_POINT_TYPE_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(CONTACT_POINT_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT(ID),
  FOREIGN KEY(CONTACT_POINT_TYPE_ID) REFERENCES CONTACT_POINT_ENTITY_GROUP.CONTACT_POINT_TYPE(ID)
);