#%RAML 1.0 Library
types:
  AttributeValue:
    properties:
      attributeValue:
        type: string
      id:
        type: string
  DeviceUserSession:
    properties:
      id:
        type: string
      name:
        type: string
  ProductCollateral:
    properties:
      product:
        items: product_eg.Product
      id:
        type: string
      uRL:
        type: string
  AttributeTranslation:
    properties:
      id:
        type: string
      translatedName:
        type: string
  ProductValidityTimePeriodUOM:
    properties:
      id:
        type: string
      name:
        type: string
      pluralName:
        type: string
  ProductAttributeSet:
    properties:
      product:
        items: product_eg.Product
      id:
        type: string
      attributeSet:
        type: string
  ProductAttributeValue:
    properties:
      product:
        items: product_eg.Product
      attributeValue:
        items: AttributeValue
      id:
        type: string
      customAttributeValue:
        type: string
      name:
        type: string
      attributeSet:
        type: string
  AttributeSetTranslation:
    properties:
      id:
        type: string
      translatedName:
        type: string
      attributeSet:
        type: string
  PriceBookEntry:
    properties:
      minRequiredQuantity:
        type: integer
      unitListPrice:
        type: integer
      product:
        items: product_eg.Product
      minRequiredOrderValue:
        type: integer
      isActive:
        type: boolean
      id:
        type: string
      maxRequiredOrderValue:
        type: integer
      useStandardPrice:
        type: boolean
      servicePeriodCount:
        type: integer
  AttributeValueTranslation:
    properties:
      translatedAttributeValue:
        type: string
      attributeValue:
        items: AttributeValue
      id:
        type: string
      translatedAttributeValueDescription:
        type: string
uses:
  product_eg: ../Product/schema.yaml
