CREATE SCHEMA IF NOT EXISTS PRODUCT_CATALOG_ENTITY_GROUP;

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_ATTRIBUTE_SET (
  ID VARCHAR(36) UNIQUE NOT NULL,
  ATTRIBUTE_SET VARCHAR(500) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATALOG (
  ACTIVE_TO_DATE DATE,
  ACTIVE_FROM_DATE DATE NOT NULL,
  ID VARCHAR(36) UNIQUE NOT NULL,
  NAME VARCHAR(500) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_TRANSLATION (
  ID VARCHAR(36) UNIQUE NOT NULL,
  TRANSLATED_NAME VARCHAR(500) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY (
  ID VARCHAR(36) UNIQUE NOT NULL,
  ACTIVE_FROM_DATE DATE NOT NULL,
  ACTIVE_TO_DATE DATE,
  NAME VARCHAR(500) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATALOG_TRANSLATION (
  ID VARCHAR(36) UNIQUE NOT NULL,
  TRANSLATED_NAME VARCHAR(500) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_PRODUCT (
  ID VARCHAR(36) UNIQUE NOT NULL,
  ACTIVE_FROM_DATE_TIME TIME NOT NULL,
  ACTIVE_TO_DATE_TIME TIME,
  PRIMARY KEY (ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_ATTRIBUTE_SET_PRODUCT_CATEGORY_JOIN (
  PRODUCT_CATEGORY_ATTRIBUTE_SET_ID  VARCHAR(36) NOT NULL,
  PRODUCT_CATEGORY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_CATEGORY_ATTRIBUTE_SET_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_ATTRIBUTE_SET(ID),
  FOREIGN KEY(PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY(ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_TRANSLATION_PRODUCT_CATEGORY_JOIN (
  PRODUCT_CATEGORY_TRANSLATION_ID  VARCHAR(36) NOT NULL,
  PRODUCT_CATEGORY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_CATEGORY_TRANSLATION_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_TRANSLATION(ID),
  FOREIGN KEY(PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY(ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_PRODUCT_CATALOG_JOIN (
  PRODUCT_CATEGORY_ID  VARCHAR(36) NOT NULL,
  PRODUCT_CATALOG_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY(ID),
  FOREIGN KEY(PRODUCT_CATALOG_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATALOG(ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_PARENT_CATEGORY_JOIN (
  PRODUCT_CATEGORY_ID_LEFT  VARCHAR(36) NOT NULL,
  PRODUCT_CATEGORY_ID_RIGHT VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_CATEGORY_ID_LEFT) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY(ID),
  FOREIGN KEY(PRODUCT_CATEGORY_ID_RIGHT) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY(ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATALOG_TRANSLATION_PRODUCT_CATALOG_JOIN (
  PRODUCT_CATALOG_TRANSLATION_ID  VARCHAR(36) NOT NULL,
  PRODUCT_CATALOG_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_CATALOG_TRANSLATION_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATALOG_TRANSLATION(ID),
  FOREIGN KEY(PRODUCT_CATALOG_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATALOG(ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_PRODUCT_PRODUCT_JOIN (
  PRODUCT_CATEGORY_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_CATEGORY_PRODUCT_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT_ENTITY_GROUP.PRODUCT(ID)
);

CREATE TABLE PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_PRODUCT_PRODUCT_CATEGORY_JOIN (
  PRODUCT_CATEGORY_PRODUCT_ID  VARCHAR(36) NOT NULL,
  PRODUCT_CATEGORY_ID VARCHAR(36) NOT NULL,
  FOREIGN KEY(PRODUCT_CATEGORY_PRODUCT_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY_PRODUCT(ID),
  FOREIGN KEY(PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATALOG_ENTITY_GROUP.PRODUCT_CATEGORY(ID)
);